/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ProofOfReservesInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "currentLiabilitiesRoot"
      | "currentReserves"
      | "getStatus"
      | "inclusionVerifier"
      | "isSolvent"
      | "lastSolvencyTimestamp"
      | "solvencyVerifier"
      | "submitSolvencyProof"
      | "transferAdmin"
      | "updateLiabilitiesRoot"
      | "updateReserves"
      | "usedNullifiers"
      | "verifyInclusion"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminTransferred"
      | "InclusionVerified"
      | "LiabilitiesRootUpdated"
      | "ReservesUpdated"
      | "SolvencyChecked"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "currentLiabilitiesRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentReserves",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getStatus", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "inclusionVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isSolvent", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastSolvencyTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "solvencyVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitSolvencyProof",
    values: [
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLiabilitiesRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReserves",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "usedNullifiers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyInclusion",
    values: [
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentLiabilitiesRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "inclusionVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isSolvent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastSolvencyTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "solvencyVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitSolvencyProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLiabilitiesRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedNullifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyInclusion",
    data: BytesLike
  ): Result;
}

export namespace AdminTransferredEvent {
  export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [oldAdmin: string, newAdmin: string];
  export interface OutputObject {
    oldAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InclusionVerifiedEvent {
  export type InputTuple = [
    nullifier: BytesLike,
    liabilitiesRoot: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    nullifier: string,
    liabilitiesRoot: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    nullifier: string;
    liabilitiesRoot: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiabilitiesRootUpdatedEvent {
  export type InputTuple = [newRoot: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [newRoot: string, timestamp: bigint];
  export interface OutputObject {
    newRoot: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReservesUpdatedEvent {
  export type InputTuple = [newReserves: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [newReserves: bigint, timestamp: bigint];
  export interface OutputObject {
    newReserves: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SolvencyCheckedEvent {
  export type InputTuple = [
    passed: boolean,
    reserves: BigNumberish,
    liabilitiesRoot: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    passed: boolean,
    reserves: bigint,
    liabilitiesRoot: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    passed: boolean;
    reserves: bigint;
    liabilitiesRoot: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProofOfReserves extends BaseContract {
  connect(runner?: ContractRunner | null): ProofOfReserves;
  waitForDeployment(): Promise<this>;

  interface: ProofOfReservesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  currentLiabilitiesRoot: TypedContractMethod<[], [string], "view">;

  currentReserves: TypedContractMethod<[], [bigint], "view">;

  getStatus: TypedContractMethod<
    [],
    [
      [boolean, bigint, string, bigint] & {
        solvent: boolean;
        reserves: bigint;
        liabilitiesRoot: string;
        lastChecked: bigint;
      }
    ],
    "view"
  >;

  inclusionVerifier: TypedContractMethod<[], [string], "view">;

  isSolvent: TypedContractMethod<[], [boolean], "view">;

  lastSolvencyTimestamp: TypedContractMethod<[], [bigint], "view">;

  solvencyVerifier: TypedContractMethod<[], [string], "view">;

  submitSolvencyProof: TypedContractMethod<
    [
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      publicSignals: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [void],
    "nonpayable"
  >;

  transferAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  updateLiabilitiesRoot: TypedContractMethod<
    [newRoot: BytesLike],
    [void],
    "nonpayable"
  >;

  updateReserves: TypedContractMethod<
    [newReserves: BigNumberish],
    [void],
    "nonpayable"
  >;

  usedNullifiers: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  verifyInclusion: TypedContractMethod<
    [
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      publicSignals: [BigNumberish, BigNumberish]
    ],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "currentLiabilitiesRoot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "currentReserves"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStatus"
  ): TypedContractMethod<
    [],
    [
      [boolean, bigint, string, bigint] & {
        solvent: boolean;
        reserves: bigint;
        liabilitiesRoot: string;
        lastChecked: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "inclusionVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isSolvent"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastSolvencyTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "solvencyVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitSolvencyProof"
  ): TypedContractMethod<
    [
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      publicSignals: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateLiabilitiesRoot"
  ): TypedContractMethod<[newRoot: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateReserves"
  ): TypedContractMethod<[newReserves: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedNullifiers"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyInclusion"
  ): TypedContractMethod<
    [
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      publicSignals: [BigNumberish, BigNumberish]
    ],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "AdminTransferred"
  ): TypedContractEvent<
    AdminTransferredEvent.InputTuple,
    AdminTransferredEvent.OutputTuple,
    AdminTransferredEvent.OutputObject
  >;
  getEvent(
    key: "InclusionVerified"
  ): TypedContractEvent<
    InclusionVerifiedEvent.InputTuple,
    InclusionVerifiedEvent.OutputTuple,
    InclusionVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "LiabilitiesRootUpdated"
  ): TypedContractEvent<
    LiabilitiesRootUpdatedEvent.InputTuple,
    LiabilitiesRootUpdatedEvent.OutputTuple,
    LiabilitiesRootUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReservesUpdated"
  ): TypedContractEvent<
    ReservesUpdatedEvent.InputTuple,
    ReservesUpdatedEvent.OutputTuple,
    ReservesUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SolvencyChecked"
  ): TypedContractEvent<
    SolvencyCheckedEvent.InputTuple,
    SolvencyCheckedEvent.OutputTuple,
    SolvencyCheckedEvent.OutputObject
  >;

  filters: {
    "AdminTransferred(address,address)": TypedContractEvent<
      AdminTransferredEvent.InputTuple,
      AdminTransferredEvent.OutputTuple,
      AdminTransferredEvent.OutputObject
    >;
    AdminTransferred: TypedContractEvent<
      AdminTransferredEvent.InputTuple,
      AdminTransferredEvent.OutputTuple,
      AdminTransferredEvent.OutputObject
    >;

    "InclusionVerified(bytes32,bytes32,uint256)": TypedContractEvent<
      InclusionVerifiedEvent.InputTuple,
      InclusionVerifiedEvent.OutputTuple,
      InclusionVerifiedEvent.OutputObject
    >;
    InclusionVerified: TypedContractEvent<
      InclusionVerifiedEvent.InputTuple,
      InclusionVerifiedEvent.OutputTuple,
      InclusionVerifiedEvent.OutputObject
    >;

    "LiabilitiesRootUpdated(bytes32,uint256)": TypedContractEvent<
      LiabilitiesRootUpdatedEvent.InputTuple,
      LiabilitiesRootUpdatedEvent.OutputTuple,
      LiabilitiesRootUpdatedEvent.OutputObject
    >;
    LiabilitiesRootUpdated: TypedContractEvent<
      LiabilitiesRootUpdatedEvent.InputTuple,
      LiabilitiesRootUpdatedEvent.OutputTuple,
      LiabilitiesRootUpdatedEvent.OutputObject
    >;

    "ReservesUpdated(uint256,uint256)": TypedContractEvent<
      ReservesUpdatedEvent.InputTuple,
      ReservesUpdatedEvent.OutputTuple,
      ReservesUpdatedEvent.OutputObject
    >;
    ReservesUpdated: TypedContractEvent<
      ReservesUpdatedEvent.InputTuple,
      ReservesUpdatedEvent.OutputTuple,
      ReservesUpdatedEvent.OutputObject
    >;

    "SolvencyChecked(bool,uint256,bytes32,uint256)": TypedContractEvent<
      SolvencyCheckedEvent.InputTuple,
      SolvencyCheckedEvent.OutputTuple,
      SolvencyCheckedEvent.OutputObject
    >;
    SolvencyChecked: TypedContractEvent<
      SolvencyCheckedEvent.InputTuple,
      SolvencyCheckedEvent.OutputTuple,
      SolvencyCheckedEvent.OutputObject
    >;
  };
}
