import {
  createCircuitCallTxInterface,
  getPublicStates,
} from '@midnight-ntwrk/midnight-js-contracts';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { FetchZkConfigProvider } from '@midnight-ntwrk/midnight-js-fetch-zk-config-provider';
import { CompiledContract } from '@midnight-ntwrk/midnight-js-protocol/compact-js';
import { StateValue } from '@midnight-ntwrk/compact-runtime';
import type { ConnectedAPI } from '@midnight-ntwrk/dapp-connector-api';
import { setNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import { config as networkConfig, CONTRACT_ADDRESS, ACTIVE_NETWORK } from '../config/network';
import { PRIVATE_STATE_ID } from '../hooks/usePrivateState';

// In Vite, we've aliased 'managed' to our contract output directory.
// The index.js is generated by the Compact compiler.
import * as AuctionContract from 'managed/contract';

// ── Custom ZK Config Provider ─────────────────────────────────────────
//
// FetchZkConfigProvider fetches from:
//   {origin}/keys/<circuitId>.verifier
//   {origin}/zkir/<circuitId>.bzkir
//
// The SDK passes circuit IDs as "<contractName>#<circuitName>"
// (e.g. "auction#bid"), but assertSafeName() rejects '#'.
// We strip the contract-name prefix before fetching.
//
class AuctionZkConfigProvider extends FetchZkConfigProvider {
  private stripPrefix(circuitId: string): string {
    return circuitId.includes('#') ? circuitId.split('#').pop()! : circuitId;
  }

  override getProverKey(circuitId: string) {
    return super.getProverKey(this.stripPrefix(circuitId));
  }

  override getVerifierKey(circuitId: string) {
    return super.getVerifierKey(this.stripPrefix(circuitId));
  }

  override getZKIR(circuitId: string) {
    return super.getZKIR(this.stripPrefix(circuitId));
  }
}

export async function createProviders(walletApi: ConnectedAPI) {
  const serviceUris = await walletApi.getConfiguration();
  const shielded = await walletApi.getShieldedAddresses();
  const unshielded = await walletApi.getUnshieldedAddress();

  const coinPublicKey = shielded.shieldedCoinPublicKey;
  const encryptionPublicKey = shielded.shieldedEncryptionPublicKey;

  const walletProvider = {
    getCoinPublicKey: () => coinPublicKey,
    getEncryptionPublicKey: () => encryptionPublicKey,
    balanceTx: async (tx: any) => {
      const balanced = await walletApi.balanceUnsealedTransaction(tx);
      return balanced.tx as any;
    },
    submitTx: async (tx: any) => walletApi.submitTransaction(tx),
  };

  const zkConfigProvider = new AuctionZkConfigProvider(
    window.location.origin,
    fetch.bind(window)
  );

  // FORCE use of our configured v4 indexer/prover.
  // The wallet extension may return v1/v3 endpoints or mismatched nodes 
  // that don't have our contract state.
  const indexerUri = networkConfig.indexer;
  const indexerWsUri = networkConfig.indexerWS;
  const proverUri = networkConfig.proofServer;

  const publicDataProvider = indexerPublicDataProvider(indexerUri, indexerWsUri);

  return {
    privateStateProvider: levelPrivateStateProvider({
      privateStateStoreName: 'auction-private-state',
      accountId: unshielded.unshieldedAddress,
      privateStoragePasswordProvider: async () => 'Midnight-Auction-Password-1!',
    }),
    publicDataProvider,
    zkConfigProvider,
    proofProvider: httpClientProofProvider(proverUri, zkConfigProvider),
    walletProvider,
    midnightProvider: walletProvider,
  };
}

// ── getContractInstance ───────────────────────────────────────────────
//
// BYPASS findDeployedContract — it calls watchForDeployTxData which uses
// a GraphQL subscription to watch the indexer and can hang indefinitely.
//
// Instead we:
//   1. Build the callTx interface directly with createCircuitCallTxInterface
//   2. Build queryState using getPublicStates + the compiled ledger() decoder
//
export async function getContractInstance(walletApi: ConnectedAPI) {
  // Required by Midnight SDK before wallet/contract operations
  const networkString = ACTIVE_NETWORK.charAt(0).toUpperCase() + ACTIVE_NETWORK.slice(1);
  setNetworkId(networkString); // e.g. "Preprod", "Preview", "Undeployed"

  const providers = await createProviders(walletApi);

  const compiledContract = CompiledContract.make('auction', AuctionContract.Contract).pipe(
    CompiledContract.withVacantWitnesses
  );

  // Register contract address with the private state provider
  providers.privateStateProvider.setContractAddress(CONTRACT_ADDRESS);

  // Initialize the private state if it doesn't exist (which findDeployedContract normally handles)
  try {
    const currentState = await providers.privateStateProvider.get(PRIVATE_STATE_ID);
    if (!currentState) {
      await providers.privateStateProvider.set(PRIVATE_STATE_ID, {});
    }
  } catch (err: any) {
    // In case the provider throws when key is missing (e.g. LevelDB NotFoundError)
    await providers.privateStateProvider.set(PRIVATE_STATE_ID, {});
  }

  // Build the call interface directly — no WebSocket subscription needed
  const rawCallTx = createCircuitCallTxInterface(
    providers as any,
    compiledContract as any,
    CONTRACT_ADDRESS,
    PRIVATE_STATE_ID
  );

  // createCircuitCallTxInterface keys circuits by their full ID (e.g. "auction#bid").
  // Normalise to short names so AuctionPanel can call callTx.bid(...) etc.
  const callTx: Record<string, any> = {};
  for (const [key, fn] of Object.entries(rawCallTx as Record<string, any>)) {
    const shortKey = key.includes('#') ? key.split('#').pop()! : key;
    callTx[shortKey] = fn;
  }


  // Build a queryState function that reads live state from the indexer
  const queryState = async () => {
    const { contractState } = await getPublicStates(
      providers.publicDataProvider as any,
      CONTRACT_ADDRESS
    );
    
    // contractState.data is a ChargedState object.
    // In Vite, module duplication can cause `instanceof` checks to fail inside the 
    // generated ledger() function. We bypass this by serializing the internal 
    // StateValue and deserializing it using the same compact-runtime instance.
    const rawStateValue = (contractState.data as any).state;
    const encodedBytes = rawStateValue.encode();
    const safeStateValue = StateValue.decode(encodedBytes);
    
    // Use the compiled contract's ledger() decoder to get typed state
    return AuctionContract.ledger(safeStateValue);
  };

  // Verify the contract is actually reachable before returning
  await queryState();

  const deployed = {
    callTx,
    queryState,
  };

  return { deployed, providers };
}
