import { findDeployedContract } from '@midnight-ntwrk/midnight-js-contracts';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { FetchZkConfigProvider } from '@midnight-ntwrk/midnight-js-fetch-zk-config-provider';
import { CompiledContract } from '@midnight-ntwrk/midnight-js-protocol/compact-js';
import type { ConnectedAPI } from '@midnight-ntwrk/dapp-connector-api';
import { config as networkConfig, CONTRACT_ADDRESS } from '../config/network';
import { PRIVATE_STATE_ID } from '../hooks/usePrivateState';

// In Vite, we've aliased 'managed' to our contract output directory.
// The index.js is generated by the Compact compiler.
import * as AuctionContract from 'managed/contract';

// ── Custom ZK Config Provider ─────────────────────────────────────────
//
// FetchZkConfigProvider fetches from:
//   {origin}/keys/<circuitId>.verifier
//   {origin}/zkir/<circuitId>.bzkir
//
// The Midnight.js SDK passes circuit IDs as "<contractName>#<circuitName>"
// (e.g. "auction#bid") but assertSafeName() rejects the '#' character.
// We strip the contract-name prefix before fetching the files.
//
class AuctionZkConfigProvider extends FetchZkConfigProvider {
  private stripPrefix(circuitId: string): string {
    // "auction#bid" → "bid"
    return circuitId.includes('#') ? circuitId.split('#').pop()! : circuitId;
  }

  override getProverKey(circuitId: string) {
    return super.getProverKey(this.stripPrefix(circuitId));
  }

  override getVerifierKey(circuitId: string) {
    return super.getVerifierKey(this.stripPrefix(circuitId));
  }

  override getZKIR(circuitId: string) {
    return super.getZKIR(this.stripPrefix(circuitId));
  }
}

// ── Promise timeout helper ────────────────────────────────────────────
function withTimeout<T>(promise: Promise<T>, ms: number, message: string): Promise<T> {
  return Promise.race([
    promise,
    new Promise<T>((_, reject) =>
      setTimeout(() => reject(new Error(message)), ms)
    ),
  ]);
}

export async function createProviders(walletApi: ConnectedAPI) {
  // Get wallet configuration directly from the DApp connector
  const serviceUris = await walletApi.getConfiguration();
  const shielded = await walletApi.getShieldedAddresses();
  const unshielded = await walletApi.getUnshieldedAddress();

  const coinPublicKey = shielded.shieldedCoinPublicKey;
  const encryptionPublicKey = shielded.shieldedEncryptionPublicKey;

  // Wallet provider implementation that delegates to the DApp Connector
  const walletProvider = {
    getCoinPublicKey: () => coinPublicKey,
    getEncryptionPublicKey: () => encryptionPublicKey,
    balanceTx: async (tx: any) => {
      const balanced = await walletApi.balanceUnsealedTransaction(tx);
      return balanced.tx as any;
    },
    submitTx: async (tx: any) => walletApi.submitTransaction(tx),
  };

  // ZK Config Provider — uses our subclass that strips the "auction#" prefix
  // Files are served at: /keys/<name>.verifier and /zkir/<name>.bzkir
  const zkConfigProvider = new AuctionZkConfigProvider(window.location.origin, fetch.bind(window));

  return {
    // 1. Private State Provider (Local Browser Storage)
    privateStateProvider: levelPrivateStateProvider({
      privateStateStoreName: 'auction-private-state',
      accountId: unshielded.unshieldedAddress,
      privateStoragePasswordProvider: async () => 'midnight-auction-password',
    }),

    // 2. Public Data Provider (Indexer)
    publicDataProvider: indexerPublicDataProvider(
      serviceUris.indexerUri || networkConfig.indexer,
      serviceUris.indexerWsUri || networkConfig.indexerWS
    ),

    // 3. ZK Config Provider
    zkConfigProvider,

    // 4. Proof Provider
    proofProvider: httpClientProofProvider(
      serviceUris.proverServerUri || networkConfig.proofServer,
      zkConfigProvider
    ),

    // 5. Wallet Provider
    walletProvider,
    midnightProvider: walletProvider,
  };
}

export async function getContractInstance(walletApi: ConnectedAPI) {
  const providers = await createProviders(walletApi);

  const compiledContract = CompiledContract.make('auction', AuctionContract.Contract).pipe(
    CompiledContract.withVacantWitnesses
  );

  // findDeployedContract calls watchForDeployTxData which can hang if the
  // indexer is slow. Wrap with a 30-second timeout to fail fast.
  const deployed = await withTimeout(
    findDeployedContract(providers as any, {
      compiledContract: compiledContract as any,
      contractAddress: CONTRACT_ADDRESS,
      privateStateId: PRIVATE_STATE_ID,
    }),
    30_000,
    `Timed out connecting to the Midnight indexer after 30 seconds. ` +
    `Please check your internet connection and try again. ` +
    `Contract address: ${CONTRACT_ADDRESS}`
  );

  return {
    deployed,
    providers,
  };
}
