/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as proofOfReservesSol from "./ProofOfReserves.sol";
export type { proofOfReservesSol };
export type { MockVerifier } from "./MockVerifier";
export * as factories from "./factories";
export { MockVerifier__factory } from "./factories/MockVerifier__factory";
export type { IGroth16Verifier } from "./ProofOfReserves.sol/IGroth16Verifier";
export { IGroth16Verifier__factory } from "./factories/ProofOfReserves.sol/IGroth16Verifier__factory";
export type { ProofOfReserves } from "./ProofOfReserves.sol/ProofOfReserves";
export { ProofOfReserves__factory } from "./factories/ProofOfReserves.sol/ProofOfReserves__factory";
